root: true
plugins:
  - import
  - react
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 2021
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  react:
    version: "17"
env:
  browser: true
  es6: true
  node: true
